spring:
   datasource:
     url: jdbc:mysql://localhost:3306/shop_manager?serverTimezone=UTC
     username: root
     password: root


mybatis:
  type-aliases-package: com.yy.springjpa.bean

application:
  name: yy-custom